---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../vendor/katalog/ingress/forecastle
  - ../../vendor/katalog/ingress/nginx
  - ../../vendor/katalog/ingress/cert-manager

  - resources/ingress.yml

patchesStrategicMerge:
  - patches/ingress-nginx-lb-annotation.yml