resources:

# Ingress
- ../../vendor/katalog/ingress/forecastle
- ../../vendor/katalog/ingress/nginx
- ../../vendor/katalog/ingress/cert-manager

# Logging
- ../../vendor/katalog/logging/cerebro
- ../../vendor/katalog/logging/curator
- ../../vendor/katalog/logging/elasticsearch-single
- ../../vendor/katalog/logging/fluentd
- ../../vendor/katalog/logging/kibana

# Monitoring
- ../../vendor/katalog/monitoring/alertmanager-operated
- ../../vendor/katalog/monitoring/goldpinger
- ../../vendor/katalog/monitoring/grafana
- ../../vendor/katalog/monitoring/kube-proxy-metrics
- ../../vendor/katalog/monitoring/kube-state-metrics
- ../../vendor/katalog/monitoring/node-exporter
- ../../vendor/katalog/monitoring/prometheus-operated
- ../../vendor/katalog/monitoring/prometheus-operator

# Custom resources
- resources/ingress.yml

# Disaster Recovery
# - ../../vendor/katalog/dr/velero/velero-gcp
# - ../../vendor/katalog/dr/velero/velero-schedules
# - resources/velero-backup-storage-location.yml
# - resources/velero-volume-snapshot-location.yml
# - resources/velero-cloud-credentials.yml

# Open Policy Agent
# - ../../vendor/katalog/opa/gatekeeper/core
# - ../../vendor/katalog/opa/gatekeeper/monitoring
# - ../../vendor/katalog/opa/gatekeeper/rules

patchesStrategicMerge:

# Ingress
- patches/ingress-nginx-lb-annotation.yml

# Logging
- patches/fluentd-resources.yml
- patches/fluentbit-resources.yml

# Monitoring
- patches/alertmanager-resources.yml
- patches/cerebro-resources.yml
- patches/elasticsearch-resources.yml
- patches/prometheus-operator-resources.yml
- patches/prometheus-resources.yml
